export const optionCurrency = {
  KRW: {
    symbol: '￦',
    initialValue: 1000000
  },
  USD: {
    symbol: '$',
    initialValue: 1000
  },
  BTC: {
    symbol: 'Ƀ',
    initialValue: 1
  }
};

export const currencies = [
  {
    name: 'KRW',
    symbol: '￦'
  },
  {
    name: 'USD',
    symbol: '$'
  },
  {
    name: 'BTC',
    symbol: 'Ƀ'
  }
];

export const sorterOptions = [
  {
    name: 'alphabet',
    text: '알파벳순'
  },
  {
    name: 'percentage',
    text: '변화율순'
  },
  {
    name: 'price',
    text: '가격순'
  },
  {
    name: 'volume',
    text: '볼륨순'
  }
];

export const currency_name = {
  '1CR': '1CRedit',
  ABY: 'ArtByte',
  AC: 'AsiaCoin',
  ACH: 'Altcoin Herald',
  ADN: 'Aiden',
  AEON: 'AEON Coin',
  AERO: 'Aerocoin',
  AIR: 'AIRcoin',
  AMP: 'Synereo AMP',
  APH: 'AphroditeCoin',
  ARCH: 'ARCHcoin',
  ARDR: 'Ardor',
  ATOM: 'Cosmos',
  AUR: 'Auroracoin',
  AXIS: 'Axis',
  BALLS: 'Snowballs',
  BANK: 'BankCoin',
  BAT: 'Basic Attention Token',
  BBL: 'BitBlock',
  BBR: 'Boolberry',
  BCC: 'BTCtalkcoin',
  BCH: 'Bitcoin Cash (FROZEN)',
  BCHABC: 'Bitcoin Cash',
  BCHBEAR: '3X Short Bitcoin Cash Token',
  BCHBULL: '3X Long Bitcoin Cash Token',
  BCHSV: 'Bitcoin SV',
  BCN: 'Bytecoin',
  BCY: 'BitCrystals',
  BDC: 'Black Dragon Coin',
  BDG: 'Badgercoin',
  BEAR: '3X Short Bitcoin Token',
  BELA: 'Bela Legacy',
  BITCNY: 'BitCNY',
  BITS: 'Bitstar',
  BITUSD: 'BitUSD',
  BLK: 'BlackCoin',
  BLOCK: 'Blocknet',
  BLU: 'BlueCoin',
  BNS: 'BonusCoin',
  BNT: 'Bancor',
  BONES: 'Bones',
  BOST: 'BoostCoin',
  BSVBEAR: '3X Short Bitcoin SV Token',
  BSVBULL: '3X Long Bitcoin SV Token',
  BTC: 'Bitcoin',
  BTCD: 'BitcoinDark',
  BTCS: 'Bitcoin-sCrypt',
  BTM: 'Bitmark',
  BTS: 'BitShares',
  BTT: 'BitTorrent',
  BULL: '3X Long Bitcoin Token',
  BURN: 'BurnerCoin',
  BURST: 'Burst',
  C2: 'Coin2.0',
  CACH: 'CACHeCoin',
  CAI: 'CaiShen',
  CC: 'Colbert Coin',
  CCN: 'Cannacoin',
  CGA: 'Cryptographic Anomaly',
  CHA: 'Chancecoin',
  CINNI: 'CinniCoin',
  CLAM: 'CLAMS',
  CNL: 'ConcealCoin',
  CNMT: 'Coinomat1',
  CNOTE: 'C-Note',
  COMM: 'CommunityCoin',
  CON: 'Coino',
  CORG: 'CorgiCoin',
  CRYPT: 'CryptCoin',
  CURE: 'Curecoin',
  CVC: 'Civic',
  CYC: 'Conspiracy Coin',
  DAO: 'The DAO',
  DASH: 'Dash',
  DCR: 'Decred',
  DGB: 'DigiByte',
  DICE: 'NeoDICE',
  DIEM: 'Diem',
  DIME: 'Dimecoin',
  DIS: 'DistroCoin',
  DNS: 'BitShares DNS',
  DOGE: 'Dogecoin',
  DRKC: 'DarkCash',
  DRM: 'Dreamcoin',
  DSH: 'Dashcoin',
  DVK: 'DvoraKoin',
  EAC: 'EarthCoin',
  EBT: 'EBTcoin',
  ECC: 'ECCoin',
  EFL: 'Electronic Gulden',
  EMC2: 'Einsteinium',
  EMO: 'EmotiCoin',
  ENC: 'Entropycoin',
  EOS: 'EOS',
  ETC: 'Ethereum Classic',
  ETH: 'Ethereum',
  ETHBEAR: '3X Short Ethereum Token',
  ETHBNT: 'Bancor Smart Token',
  ETHBULL: '3X Long Ethereum Token',
  eTOK: 'eToken',
  EXE: 'Execoin',
  EXP: 'Expanse',
  FAC: 'Faircoin',
  FCN: 'Fantomcoin',
  FCT: 'Factom',
  FIBRE: 'Fibrecoin',
  FLAP: 'FlappyCoin',
  FLDC: 'FoldingCoin',
  FLO: 'Florincoin',
  FLT: 'FlutterCoin',
  FOAM: 'Foam',
  FOX: 'FoxCoin',
  FRAC: 'Fractalcoin',
  FRK: 'Franko',
  FRQ: 'FairQuark',
  FVZ: 'FVZCoin',
  FZ: 'Frozen',
  FZN: 'Fuzon',
  GAME: 'GameCredits',
  GAP: 'Gapcoin',
  GAS: 'Gas',
  GDN: 'Global Denomination',
  GEMZ: 'GetGems',
  GEO: 'GeoCoin',
  GIAR: 'Giarcoin',
  GLB: 'Globe',
  GML: 'GameleagueCoin',
  GNO: 'Gnosis',
  GNS: 'GenesisCoin',
  GNT: 'Golem',
  GOLD: 'GoldEagles',
  GPC: 'GROUPCoin',
  GPUC: 'GPU Coin',
  GRC: 'Gridcoin Research',
  GRCX: 'Gridcoin',
  GRIN: 'Grin',
  GRS: 'Groestlcoin',
  GUE: 'Guerillacoin',
  H2O: 'H2O Coin',
  HIRO: 'Hirocoin',
  HOT: 'Hotcoin',
  HUC: 'Huntercoin',
  HUGE: 'BIGcoin',
  HVC: 'Heavycoin',
  HYP: 'HyperStake',
  HZ: 'Horizon',
  IFC: 'Infinitecoin',
  INDEX: 'CoinoIndex',
  IOC: 'IO Digital Currency',
  ITC: 'Information Coin',
  IXC: 'iXcoin',
  JLH: 'jl777hodl',
  JPC: 'JackpotCoin',
  JUG: 'JuggaloCoin',
  KDC: 'KlondikeCoin',
  KEY: 'KeyCoin',
  KNC: 'Kyber',
  LBC: 'LBRY Credits',
  LC: 'Limecoin',
  LCL: 'Limecoin Lite',
  LEAF: 'Leafcoin',
  LGC: 'Logicoin',
  LINK: 'Chainlink',
  LOL: 'LeagueCoin',
  LOOM: 'LOOM Network',
  LOVE: 'LOVEcoin',
  LPT: 'Livepeer',
  LQD: 'LIQUID',
  LSK: 'Lisk',
  LTBC: 'LTBCoin',
  LTC: 'Litecoin',
  LTCX: 'LiteCoinX',
  MAID: 'MaidSafeCoin',
  MANA: 'Decentraland',
  MAST: 'MastiffCoin',
  MATIC: 'Matic Network',
  MAX: 'MaxCoin',
  MCN: 'Moneta Verde',
  MEC: 'Megacoin',
  METH: 'CryptoMETH',
  MIL: 'Millennium Coin',
  MIN: 'Minerals',
  MINT: 'Mintcoin',
  MKR: 'Maker',
  MMC: 'MemoryCoin',
  MMNXT: 'MMNXT',
  MMXIV: 'Maieuticoin',
  MNTA: 'Moneta',
  MON: 'Monocle',
  MRC: 'microCoin',
  MRS: 'Marscoin',
  MTS: 'Metiscoin',
  MUN: 'Muniti',
  MYR: 'Myriadcoin',
  MZC: 'MazaCoin',
  N5X: 'N5coin',
  NAS: 'NAS',
  NAUT: 'Nautiluscoin',
  NAV: 'NAVCoin',
  NBT: 'NuBits',
  NEOS: 'Neoscoin',
  NL: 'Nanolite',
  NMC: 'Namecoin',
  NMR: 'Numeraire',
  NOBL: 'NobleCoin',
  NOTE: 'DNotes',
  NOXT: 'NobleNXT',
  NRS: 'NoirShares',
  NSR: 'NuShares',
  NTX: 'NTX',
  NXC: 'Nexium',
  NXT: 'NXT',
  NXTI: 'NXTInspect',
  OMG: 'OmiseGO',
  OMNI: 'Omni',
  OPAL: 'Opal',
  PAND: 'PandaCoin',
  PASC: 'PascalCoin',
  PAWN: 'Pawncoin',
  PAX: 'Paxos Standard',
  PIGGY: 'New Piggycoin',
  PINK: 'Pinkcoin',
  PLX: 'ParallaxCoin',
  PMC: 'Premine',
  POLY: 'Polymath',
  POT: 'PotCoin',
  PPC: 'Peercoin',
  PRC: 'ProsperCoin',
  PRT: 'Particle',
  PTS: 'BitShares PTS',
  Q2C: 'QubitCoin',
  QBK: 'Qibuck',
  QCN: 'QuazarCoin',
  QORA: 'Qora',
  QTL: 'Quatloo',
  QTUM: 'Qtum',
  RADS: 'Radium',
  RBY: 'Rubycoin',
  RDD: 'Reddcoin',
  REP: 'Augur',
  RIC: 'Riecoin',
  RZR: 'Razor',
  SBD: 'Steem Dollars',
  SC: 'Siacoin',
  SDC: 'Shadow',
  SHIBE: 'ShibeCoin',
  SHOPX: 'ShopX',
  SILK: 'Silkcoin',
  SJCX: 'Storjcoin X',
  SLR: 'SolarCoin',
  SMC: 'SmartCoin',
  SNT: 'Status',
  SNX: 'Synthetix Network Token',
  SOC: 'SocialCoin',
  SPA: 'Spaincoin',
  SQL: 'Squallcoin',
  SRCC: 'SourceCoin',
  SRG: 'Surge',
  SSD: 'Sonic',
  STEEM: 'STEEM',
  STORJ: 'Storj',
  STR: 'Stellar',
  STRAT: 'Stratis',
  SUM: 'SummerCoin',
  SUN: 'Suncoin',
  SWARM: 'SWARM',
  SXC: 'Sexcoin',
  SYNC: 'Sync',
  SYS: 'Syscoin',
  TAC: 'Talkcoin',
  TOR: 'TorCoin',
  TRUST: 'TrustPlus',
  TRX: 'Tron',
  TRXBEAR: '3X Short TRX Token',
  TRXBULL: '3X Long TRX Token',
  TWE: 'Twecoin',
  UIS: 'Unitus',
  ULTC: 'Umbrella-LTC',
  UNITY: 'SuperNET',
  URO: 'Uro',
  USDC: 'USD Coin',
  USDE: 'USDE',
  USDJ: 'USDJ',
  USDT: 'Tether USD',
  UTC: 'UltraCoin',
  UTIL: 'UtilityCoin',
  UVC: 'UniversityCoin',
  VIA: 'Viacoin',
  VOOT: 'VootCoin',
  VOX: 'Voxels',
  VRC: 'VeriCoin',
  VTC: 'Vertcoin',
  WC: 'WhiteCoin',
  WDC: 'Worldcoin',
  WIKI: 'Wikicoin',
  WIN: 'WINK',
  WOLF: 'InsanityCoin',
  X13: 'X13Coin',
  XAI: 'Sapience AIFX',
  XAP: 'API Coin',
  XBC: 'BitcoinPlus',
  XC: 'XCurrency',
  XCH: 'ClearingHouse',
  XCN: 'Cryptonite',
  XCP: 'Counterparty',
  XCR: 'Crypti',
  XDN: 'DigitalNote',
  XDP: 'Dogeparty',
  XEM: 'NEM',
  XHC: 'Honorcoin',
  XLB: 'Libertycoin',
  XMG: 'Magi',
  XMR: 'Monero',
  XPB: 'Pebblecoin',
  XPM: 'Primecoin',
  XRP: 'Ripple',
  XSI: 'Stability Shares',
  XST: 'StealthCoin',
  XSV: 'Silicon Valley Coin',
  XTZ: 'Tezos',
  XUSD: 'CoinoUSD',
  XVC: 'Vcash',
  XXC: 'CREDS',
  YACC: 'YACCoin',
  YANG: 'Yangcoin',
  YC: 'YellowCoin',
  YIN: 'Yincoin',
  ZEC: 'Zcash',
  ZRX: '0x'
};
